#!/bin/bash
# confirm bigip1 and bigip2 are active
for i in {1..12}; do [ "$(sudo ssh root@192.168.1.31 cat /var/prompt/ps1)" = "Active" ] && break; sleep 5; done
touch /home/student/Desktop/bigip1_ready
for i in {1..12}; do [ "$(sudo ssh root@192.168.2.31 cat /var/prompt/ps1)" = "Active" ] && break; sleep 5; done
touch /home/student/Desktop/bigip2_ready
